name: publish
on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci  # Clean install for consistency

      - name: Run tests
        run: npm test  # Assuming you have tests in package.json scripts

      - name: Build package
        run: npm run build  # Build both ESM and CJS versions

      - name: Verify build
        run: |
          ls -la dist/
          [ -f dist/cjs/index.js ] || exit 1
          [ -f dist/esm/index.js ] || exit 1
          [ -f dist/types/index.d.ts ] || exit 1

      - name: Publish to npm
        run: npm publish ./dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Requires npm auth token in secrets

      - name: Create GitHub Release
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            This release includes:
            - Dual ESM/CJS module support
            - Cloudinary service integration
            - TypeScript definitions
          draft: false
          prerelease: false